const STOPWORDS = new Set([
  "a", "about", "above", "after", "again", "against", "all", "am", "an",
  "and", "any", "are", "aren't", "as", "at", "be", "because", "been",
  "before", "being", "below", "between", "both", "but", "by", "can",
  "can't", "cannot", "could", "couldn't", "did", "didn't", "do", "does",
  "doesn't", "doing", "don't", "down", "during", "each", "few", "for",
  "from", "further", "get", "gets", "got", "had", "hadn't", "has",
  "hasn't", "have", "haven't", "having", "he", "he'd", "he'll", "he's",
  "her", "here", "here's", "hers", "herself", "him", "himself", "his",
  "how", "how's", "i", "i'd", "i'll", "i'm", "i've", "if", "in", "into",
  "is", "isn't", "it", "it's", "its", "itself", "just", "let", "let's",
  "like", "make", "may", "me", "might", "more", "most", "much", "must",
  "mustn't", "my", "myself", "no", "nor", "not", "now", "of", "off",
  "on", "once", "only", "or", "other", "ought", "our", "ours", "ourselves",
  "out", "over", "own", "per", "put", "quite", "rather", "re",
  "really", "right", "s", "said", "same", "say", "says", "sha", "shall",
  "shan't", "she", "she'd", "she'll", "she's", "should", "shouldn't",
  "since", "so", "some", "something", "still", "such", "t", "take", "than",
  "that", "that's", "the", "their", "theirs", "them", "themselves", "then",
  "there", "there's", "these", "they", "they'd", "they'll", "they're",
  "they've", "this", "those", "through", "to", "too", "under", "until",
  "up", "us", "use", "used", "using", "very", "want", "was", "wasn't",
  "we", "we'd", "we'll", "we're", "we've", "were", "weren't", "what",
  "what's", "when", "when's", "where", "where's", "which", "while", "who",
  "who's", "whom", "why", "why's", "will", "with", "won't", "would",
  "wouldn't", "you", "you'd", "you'll", "you're", "you've", "your",
  "yours", "yourself", "yourselves",
  "also", "already", "always", "another", "around", "away", "back",
  "became", "become", "becomes", "becoming", "behind", "beside", "besides",
  "best", "better", "big", "come", "comes", "coming", "day", "days",
  "different", "done", "end", "enough", "even", "every", "example",
  "find", "first", "found", "give", "given", "go", "going", "gone",
  "good", "great", "help", "here", "high", "however", "include",
  "including", "instead", "keep", "kind", "know", "known", "large",
  "last", "later", "least", "less", "long", "look", "looking", "made",
  "many", "means", "need", "needs", "never", "new", "next", "number",
  "often", "old", "one", "ones", "order", "others", "people", "place",
  "point", "possible", "problem", "provide", "provides", "read",
  "result", "run", "running", "see", "set", "several", "show", "shows",
  "side", "simply", "small", "start", "started", "thing",
  "things", "think", "three", "time", "times", "today", "together",
  "top", "turn", "two", "understand", "upon", "us", "way",
  "ways", "well", "without", "work", "working", "works", "world",
  "write", "year", "years", "yet",
  "able", "across", "actually", "almost", "along", "among",
  "call", "called", "case", "certain", "change", "changes", "clear",
  "common", "complete", "consider",
  "early", "easily", "either", "entire",
  "especially", "ever", "fact", "far", "follow", "following", "form",
  "full", "general", "hand", "important", "information", "interest",
  "level", "line", "little", "main", "makes", "mean",
  "move", "name", "note", "nothing", "open", "part", "particular",
  "pass", "passed", "perhaps", "play", "power", "present",
  "put", "quite", "rather", "real", "reason", "require",
  "return", "returns", "second", "sense", "simple", "single", "social",
  "special", "specific", "step", "support", "sure", "take",
  "tell", "terms", "thought", "true", "try", "turn", "value", "values",
  "want", "whole", "word", "words",
  "article", "click", "content", "page", "post", "share", "sign",
  "story", "member", "response", "follow", "written", "reading",
  "minutes", "ago", "published"
]);
